### ISSUE TITLE
expectTypeOf allows an incorrect any value instead of the specified type

### ISSUE THREAD

**Issue by kwangure** [mmkal/expect-type#38] opened 2023-10-02 08:39 UTC
When I use `expectTypeOf`, I expect it to fail when I pass `any` as input. For example, `toBeString()` should strictly only allow strings and not any other type...including `any`.

```ts
expectTypeOf(1).toBeString(); //  Fails 👍
expectTypeOf(1 as any).toBeString(); // Passes 👎
```

This is particular useful in cases when your types reason about `any`, I need to strictly know that a type will fail if its `any` or not. For example:

```ts
type IsAny<T> = 0 extends 1 & T ? true : false;

export type CustomType<T> = IsAny<T> extends true ? number: any;
```
If I use `CustomType` somewhere, I'd like to test `expectTypeOf(value).toBeNumber();` and have it fail if it's `any` when I don't expect it to be.

This issue was originally opened at https://github.com/vitest-dev/vitest/issues/4205.

**Comment by mmkal** [comment] 2023-10-02 11:32
This will be fixed by #16. And looks to be a duplicate of https://github.com/mmkal/expect-type/issues/32. If you're using expect-type directly, you can try the `next` dist tag now. The version in vitest will be bumped by https://github.com/vitest-dev/vitest/pull/4206. Simplest thing to do will just be to wait for that.

**Closed** 2023-10-03 01:34 UTC
